name: Doxygen
on:
  push:
    branches:
      - 'main'
      - 'doxygen'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: DenverCoder1/doxygen-github-pages-action@v2.0.
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
